### ISSUE TITLE
Base setup for project

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-chip-shop#1]
[Epic: 1 ](https://github.com/EdelCorbett/the-chip-shop/milestone/1)

As a  **Developer** I can **setup a project** so that **begin project**

**Acceptance Criteria**
1. Create a Django project 
2. Create the base structure of the project

**Tasks**
- [x] Create  virtual environment 
- [x] Install Django and gunicorn
- [x] Install psycopg2
- [x] Start Django project
- [x] Create App name and add to INSTALLED APPS in settings.py
- [x] Create env.py and .gitignore files
- [x] Add secret keys to env.py 
- [x] Add env.py to .gitignore file
- [x] Create requirements.txt file
