### ISSUE TITLE
Delivery or collection

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-chip-shop#10]
[Epic: 4 ]()
As a customer, I want to be able to place an order for delivery or collection

**Acceptance Criteria**

1. If I choose delivery, I should be prompted to enter my delivery address
2. If I choose collection, I should see instructions for where to collect my order.
3. After selecting delivery or collection, I should proceed to the payment step

**Task**

- [ ] Create views and templates for delivery and collection
- [ ] Create form for delivery address 
- [ ] Message for collection 
- [ ] successful order message
