### ISSUE TITLE
Admin view customer orders

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-chip-shop#16]
[Epic: 7](https://github.com/EdelCorbett/the-chip-shop/milestone/7)

As an admin, I want to be able to view and manage customer orders.

**Acceptance Criteria**

1. Access to an admin dashboard where I can view all customer orders
2.  Order should display details such as the order number, customer name, date/time placed, items ordered, total amount

**Task**

- [ ] Implement an admin panel dashboard to display an overview of all customer orders
- [ ] Options to filter and search orders by different criteria
- [ ]  Details for each order, including the order number, customer name, date/time placed, items ordered, total amount
