### ISSUE TITLE
Admin- customer inquiries

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-chip-shop#18]
[Epic: 1 ]()
As a **Admin** I can **view customer inquiries** so that **i can contact and follow up on their inquiry**

**Acceptance Criteria**

1. Section where I can view all customer inquiries
2. Inquiry should display details such as the customer's name, email address, inquiry subject, and message content
3. Mark inquiries as read or unread, as well as update their status 

**Task**

- [ ] create inquiries app
- [ ] implement required fields
- [ ] Add read/unread and status
