### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-chip-shop#3]
[Epic: 1 ](https://github.com/EdelCorbett/the-chip-shop/milestone/1)
As a Developer I can Deploy project early so that I can continually test the application during development

**Acceptance Criteria**

1. Deployed application on Heroku

**Task**

- [ ] Create new app in Heroku
- [ ] Add config vars in settings
- [ ] Create Procfile for gunicorn
- [ ] Add requirments.txt
- [ ] Deploy to heroku
