### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by EdelCorbett** [EdelCorbett/the-chip-shop#6]
[Epic: 2 ]()
As a user I can login so that I can make an order

**Acceptance Criteria**

1. User can login using their username and password.
2. validates input fields in form
3. User directed to menu page after successful login

**Task**

- [ ] login in button on home page
- [ ] Create a log in form 
- [ ] functionality to authenticate users
- [ ] display menu after successfully login
